// <auto-generated />
using System;
using FastStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastStore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228224448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastStore.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Calzado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ropa Superior"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pantalones"
                        });
                });

            modelBuilder.Entity("FastStore.Api.Models.OrdenReposicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesReposicion");
                });

            modelBuilder.Entity("FastStore.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nombre = "Tenis Nike Air Max 270 - Talla 40",
                            Precio = 580000m,
                            StockActual = 15,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Nombre = "Tenis Adidas Ultraboost - Talla 38",
                            Precio = 620000m,
                            StockActual = 2,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Nombre = "Camiseta Básica Oversize Blanca - M",
                            Precio = 85000m,
                            StockActual = 50,
                            StockMinimo = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Nombre = "Hoodie Negro Algodón - L",
                            Precio = 145000m,
                            StockActual = 4,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Nombre = "Jeans Slim Fit Azul - Talla 32",
                            Precio = 180000m,
                            StockActual = 25,
                            StockMinimo = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Nombre = "Joggers de Entrenamiento Gris - S",
                            Precio = 120000m,
                            StockActual = 3,
                            StockMinimo = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Nombre = "Tenis Puma Rider - Talla 41",
                            Precio = 320000m,
                            StockActual = 12,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Nombre = "Chaqueta Denim Clásica - M",
                            Precio = 210000m,
                            StockActual = 1,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            Nombre = "Shorts Deportivos Pro - L",
                            Precio = 95000m,
                            StockActual = 30,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            Nombre = "Tenis Jordan Retro 1 - Talla 42",
                            Precio = 850000m,
                            StockActual = 2,
                            StockMinimo = 3
                        });
                });

            modelBuilder.Entity("FastStore.Api.Models.OrdenReposicion", b =>
                {
                    b.HasOne("FastStore.Api.Models.Producto", "Producto")
                        .WithMany("OrdenesReposicion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FastStore.Api.Models.Producto", b =>
                {
                    b.HasOne("FastStore.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FastStore.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("FastStore.Api.Models.Producto", b =>
                {
                    b.Navigation("OrdenesReposicion");
                });
#pragma warning restore 612, 618
        }
    }
}
